<?php
session_start();
include_once('../server/scaleCount.php');
include_once('factorK.php');

$scale_D = function($answer) use($true, $false){ $count = 0; $count += $false($answer[1]); $count += $true($answer[4]); $count += $false($answer[8]); $count += $false($answer[9]); $count += $true($answer[14]); $count += $true($answer[17]); $count += $false($answer[19]); $count += $false($answer[28]); $count += $true($answer[30]); $count += $false($answer[32]); $count += $false($answer[36]); $count += $true($answer[37]); $count += $true($answer[38]); $count += $false($answer[42]); $count += $false($answer[44]); $count += $true($answer[45]); $count += $false($answer[48]); $count += $false($answer[54]); $count += $true($answer[55]); $count += $false($answer[67]); $count += $true($answer[72]); $count += $false($answer[74]); $count += $false($answer[75]); $count += $true($answer[91]); $count += $false($answer[94]); $count += $false($answer[108]); $count += $true($answer[116]); $count += $false($answer[117]); $count += $true($answer[126]); $count += $true($answer[129]); $count += $false($answer[133]); $count += $false($answer[139]); $count += $false($answer[140]); $count += $false($answer[141]); $count += $false($answer[142]); $count += $true($answer[145]); $count += $true($answer[146]); $count += $false($answer[147]); $count += $false($answer[164]); $count += $true($answer[169]); $count += $true($answer[174]); $count += $false($answer[177]); $count += $true($answer[180]); $count += $false($answer[187]); $count += $false($answer[188]); $count += $false($answer[211]); $count += $false($answer[222]); $count += $false($answer[225]); $count += $true($answer[232]); $count += $false($answer[237]); $count += $false($answer[244]); $count += $false($answer[247]); $count += $false($answer[259]); $count += $false($answer[266]); $count += $false($answer[329]); return $count; };

$scale_Dp = function($answer) use($true, $false){ $count = 0; $count += $false($answer[8]); $count += $false($answer[11]); $count += $true($answer[16]); $count += $true($answer[20]); $count += $true($answer[21]); $count += $true($answer[30]); $count += $true($answer[31]); $count += $false($answer[33]); $count += $true($answer[34]); $count += $true($answer[41]); $count += $true($answer[51]); $count += $true($answer[53]); $count += $true($answer[55]); $count += $false($answer[69]); $count += $true($answer[70]); $count += $false($answer[78]); $count += $true($answer[81]); $count += $false($answer[82]); $count += $true($answer[88]); $count += $true($answer[93]); $count += $false($answer[94]); $count += $true($answer[98]); $count += $true($answer[104]); $count += $true($answer[112]); $count += $false($answer[121]); $count += $false($answer[124]); $count += $false($answer[128]); $count += $false($answer[142]); $count += $false($answer[156]); $count += $false($answer[157]); $count += $false($answer[159]); $count += $false($answer[166]); $count += $false($answer[170]); $count += $false($answer[184]); $count += $true($answer[194]); $count += $true($answer[201]); $count += $false($answer[208]); $count += $false($answer[213]); $count += $false($answer[216]); $count += $true($answer[218]); $count += $true($answer[224]); $count += $false($answer[225]); $count += $false($answer[242]); $count += $true($answer[258]); $count += $false($answer[260]); $count += $false($answer[262]); $count += $true($answer[263]); $count += $false($answer[265]); $count += $false($answer[266]); $count += $true($answer[287]); return $count; };

$scale_Es = function($answer) use($true, $false){ $count = 0; $count += $false($answer[5]); $count += $false($answer[8]); $count += $false($answer[11]); $count += $true($answer[15]); $count += $true($answer[16]); $count += $true($answer[20]); $count += $true($answer[21]); $count += $true($answer[22]); $count += $true($answer[30]); $count += $true($answer[31]); $count += $false($answer[33]); $count += $true($answer[34]); $count += $true($answer[37]); $count += $true($answer[41]); $count += $true($answer[43]); $count += $true($answer[45]); $count += $true($answer[47]); $count += $true($answer[64]); $count += $true($answer[84]); $count += $false($answer[89]); $count += $false($answer[90]); $count += $true($answer[91]); $count += $false($answer[105]); $count += $true($answer[137]); $count += $true($answer[144]); $count += $true($answer[146]); $count += $false($answer[164]); $count += $true($answer[165]); $count += $true($answer[167]); $count += $true($answer[169]); $count += $false($answer[176]); $count += $false($answer[178]); $count += $true($answer[179]); $count += $true($answer[181]); $count += $true($answer[189]); $count += $false($answer[191]); $count += $false($answer[209]); $count += $true($answer[217]); $count += $true($answer[220]); $count += $true($answer[228]); $count += $true($answer[232]); $count += $true($answer[233]); $count += $true($answer[241]); $count += $true($answer[246]); $count += $true($answer[251]); $count += $false($answer[254]); $count += $true($answer[255]); $count += $true($answer[267]); $count += $true($answer[272]); $count += $true($answer[273]); $count += $false($answer[275]); $count += $true($answer[276]); $count += $false($answer[277]); $count += $true($answer[278]); $count += $false($answer[279]); $count += $true($answer[280]); $count += $true($answer[286]); $count += $false($answer[289]); $count += $true($answer[290]); $count += $true($answer[291]); $count += $false($answer[294]); $count += $true($answer[295]); $count += $true($answer[297]); $count += $true($answer[298]); $count += $true($answer[302]); $count += $true($answer[306]); $count += $true($answer[310]); $count += $true($answer[315]); $count += $true($answer[318]); $count += $true($answer[319]); $count += $true($answer[321]); $count += $true($answer[322]); $count += $true($answer[324]); $count += $true($answer[328]); $count += $true($answer[331]); $count += $true($answer[332]); $count += $false($answer[342]); $count += $true($answer[354]); return $count; };

$scale_F = function($answer) use($true, $false){ $count = 0; $count += $false($answer[5]); $count += $false($answer[11]); $count += $true($answer[17]); $count += $true($answer[23]); $count += $true($answer[29]); $count += $true($answer[35]); $count += $true($answer[41]); $count += $true($answer[47]); $count += $true($answer[53]); $count += $true($answer[59]); $count += $true($answer[65]); $count += $true($answer[71]); $count += $false($answer[77]); $count += $true($answer[83]); $count += $false($answer[89]); $count += $true($answer[95]); $count += $false($answer[101]); $count += $false($answer[107]); $count += $true($answer[113]); $count += $false($answer[119]); $count += $false($answer[125]); $count += $false($answer[131]); $count += $true($answer[137]); $count += $true($answer[143]); $count += $true($answer[149]); $count += $true($answer[155]); $count += $true($answer[161]); $count += $true($answer[167]); $count += $false($answer[173]); $count += $true($answer[179]); $count += $false($answer[185]); $count += $false($answer[191]); $count += $true($answer[197]); $count += $false($answer[203]); $count += $false($answer[209]); $count += $true($answer[215]); $count += $false($answer[221]); $count += $true($answer[227]); $count += $true($answer[233]); $count += $true($answer[239]); $count += $true($answer[245]); $count += $true($answer[251]); $count += $true($answer[257]); $count += $true($answer[263]); $count += $true($answer[269]); $count += $false($answer[275]); $count += $true($answer[281]); $count += $true($answer[287]); $count += $true($answer[293]); $count += $true($answer[299]); $count += $true($answer[305]); $count += $true($answer[311]); $count += $false($answer[317]); $count += $true($answer[323]); $count += $false($answer[329]); $count += $true($answer[335]); $count += $false($answer[342]); $count += $true($answer[348]); $count += $true($answer[354]); $count += $true($answer[360]); return $count; };

$scale_Hi = function($answer) use($true, $false){ $count = 0; $count += $false($answer[1]); $count += $false($answer[2]); $count += $false($answer[6]); $count += $false($answer[7]); $count += $false($answer[8]); $count += $false($answer[9]); $count += $true($answer[10]); $count += $false($answer[13]); $count += $true($answer[17]); $count += $false($answer[25]); $count += $false($answer[28]); $count += $true($answer[30]); $count += $true($answer[38]); $count += $true($answer[39]); $count += $true($answer[43]); $count += $false($answer[44]); $count += $false($answer[46]); $count += $false($answer[57]); $count += $true($answer[64]); $count += $false($answer[75]); $count += $false($answer[80]); $count += $false($answer[90]); $count += $false($answer[94]); $count += $false($answer[97]); $count += $true($answer[100]); $count += $false($answer[109]); $count += $false($answer[114]); $count += $false($answer[115]); $count += $false($answer[123]); $count += $false($answer[124]); $count += $false($answer[128]); $count += $false($answer[134]); $count += $false($answer[140]); $count += $false($answer[147]); $count += $false($answer[150]); $count += $false($answer[151]); $count += $false($answer[156]); $count += $false($answer[158]); $count += $false($answer[160]); $count += $false($answer[163]); $count += $true($answer[165]); $count += $false($answer[166]); $count += $true($answer[171]); $count += $false($answer[172]); $count += $true($answer[174]); $count += $false($answer[175]); $count += $false($answer[178]); $count += $false($answer[184]); $count += $false($answer[192]); $count += $false($answer[207]); $count += $false($answer[212]); $count += $false($answer[217]); $count += $false($answer[223]); $count += $true($answer[229]); $count += $false($answer[240]); $count += $false($answer[242]); $count += $false($answer[248]); $count += $false($answer[252]); $count += $false($answer[262]); $count += $false($answer[264]); return $count; };

$scale_Hs = function($answer) use($true, $false){ $count = 0; $count += $false($answer[1]); $count += $false($answer[2]); $count += $false($answer[7]); $count += $false($answer[9]); $count += $true($answer[17]); $count += $false($answer[19]); $count += $true($answer[27]); $count += $true($answer[38]); $count += $false($answer[44]); $count += $false($answer[46]); $count += $true($answer[52]); $count += $false($answer[56]); $count += $true($answer[58]); $count += $false($answer[90]); $count += $true($answer[96]); $count += $true($answer[100]); $count += $true($answer[110]); $count += $false($answer[116]); $count += $false($answer[140]); $count += $false($answer[142]); $count += $true($answer[148]); $count += $false($answer[151]); $count += $false($answer[163]); $count += $false($answer[172]); $count += $true($answer[174]); $count += $false($answer[175]); $count += $false($answer[178]); $count += $false($answer[207]); $count += $false($answer[223]); $count += $true($answer[246]); $count += $false($answer[248]); $count += $false($answer[254]); return $count; };

$scale_Is = function($answer) use($true, $false){ $count = 0; $count += $false($answer[28]); $count += $false($answer[36]); $count += $false($answer[57]); $count += $false($answer[75]); $count += $true($answer[82]); $count += $false($answer[109]); $count += $false($answer[115]); $count += $false($answer[121]); $count += $false($answer[126]); $count += $false($answer[129]); $count += $false($answer[135]); $count += $false($answer[147]); $count += $false($answer[156]); $count += $false($answer[157]); $count += $false($answer[166]); $count += $false($answer[170]); $count += $false($answer[195]); $count += $false($answer[212]); $count += $false($answer[242]); $count += $false($answer[266]); $count += $false($answer[283]); $count += $false($answer[289]); $count += $false($answer[329]); $count += $false($answer[337]); $count += $false($answer[338]); $count += $false($answer[340]); $count += $false($answer[345]); $count += $false($answer[347]); $count += $false($answer[355]); $count += $false($answer[364]); return $count; };

$scale_K = function($answer) use($false){ $count = 0; $count += $false($answer[15]); $count += $false($answer[28]); $count += $false($answer[40]); $count += $false($answer[50]); $count += $false($answer[76]); $count += $false($answer[92]); $count += $false($answer[101]); $count += $false($answer[106]); $count += $false($answer[122]); $count += $false($answer[138]); $count += $false($answer[152]); $count += $false($answer[182]); $count += $false($answer[202]); $count += $false($answer[231]); $count += $false($answer[259]); return $count; };

$scale_L = function($answer) use($true, $false){ $count = 0; $count += $true($answer[12]); $count += $true($answer[14]); $count += $true($answer[20]); $count += $true($answer[22]); $count += $true($answer[49]); $count += $true($answer[54]); $count += $true($answer[60]); $count += $true($answer[84]); $count += $true($answer[86]); $count += $false($answer[87]); $count += $false($answer[92]); $count += $true($answer[97]); $count += $false($answer[99]); $count += $false($answer[105]); $count += $false($answer[106]); $count += $true($answer[112]); $count += $true($answer[121]); $count += $true($answer[130]); $count += $false($answer[135]); $count += $true($answer[144]); $count += $false($answer[153]); $count += $true($answer[154]); $count += $false($answer[157]); $count += $false($answer[166]); $count += $true($answer[167]); $count += $true($answer[168]); $count += $true($answer[181]); $count += $true($answer[189]); $count += $true($answer[199]); $count += $true($answer[204]); $count += $true($answer[205]); $count += $true($answer[210]); $count += $true($answer[211]); $count += $true($answer[217]); $count += $true($answer[219]); $count += $true($answer[226]); $count += $true($answer[228]); $count += $true($answer[237]); $count += $true($answer[241]); $count += $false($answer[242]); $count += $true($answer[243]); $count += $true($answer[247]); $count += $true($answer[249]); $count += $true($answer[252]); $count += $false($answer[262]); $count += $true($answer[268]); return $count; };

$scale_Ma = function($answer) use($true, $false){ $count = 0; $count += $false($answer[0]); $count += $true($answer[3]); $count += $false($answer[18]); $count += $true($answer[24]); $count += $false($answer[25]); $count += $false($answer[26]); $count += $true($answer[61]); $count += $false($answer[62]); $count += $true($answer[63]); $count += $true($answer[66]); $count += $false($answer[67]); $count += $false($answer[68]); $count += $true($answer[73]); $count += $false($answer[75]); $count += $true($answer[79]); $count += $false($answer[85]); $count += $false($answer[102]); $count += $false($answer[103]); $count += $false($answer[106]); $count += $true($answer[111]); $count += $true($answer[118]); $count += $false($answer[119]); $count += $true($answer[120]); $count += $true($answer[121]); $count += $true($answer[127]); $count += $false($answer[131]); $count += $false($answer[132]); $count += $true($answer[136]); $count += $false($answer[162]); $count += $false($answer[165]); $count += $true($answer[176]); $count += $false($answer[183]); $count += $true($answer[186]); $count += $true($answer[190]); $count += $false($answer[192]); $count += $false($answer[193]); $count += $true($answer[195]); $count += $false($answer[196]); $count += $false($answer[198]); $count += $false($answer[200]); $count += $true($answer[204]); $count += $false($answer[206]); $count += $false($answer[208]); $count += $true($answer[218]); $count += $false($answer[230]); $count += $false($answer[234]); $count += $true($answer[235]); $count += $false($answer[236]); $count += $false($answer[238]); $count += $true($answer[250]); $count += $false($answer[253]); $count += $true($answer[255]); $count += $false($answer[256]); $count += $false($answer[267]); $count += $true($answer[270]); $count += $false($answer[271]); return $count; };

$scale_Mff = function($answer) use($true, $false){ $count = 0; $count += $true($answer[15]); $count += $true($answer[16]); $count += $true($answer[21]); $count += $true($answer[22]); $count += $true($answer[23]); $count += $true($answer[41]); $count += $false($answer[80]); $count += $false($answer[94]); $count += $false($answer[97]); $count += $true($answer[98]); $count += $false($answer[99]); $count += $false($answer[103]); $count += $false($answer[109]); $count += $true($answer[112]); $count += $true($answer[137]); $count += $true($answer[143]); $count += $true($answer[144]); $count += $true($answer[145]); $count += $true($answer[161]); $count += $true($answer[233]); $count += $false($answer[243]); $count += $false($answer[254]); $count += $true($answer[258]); $count += $false($answer[265]); $count += $true($answer[270]); $count += $true($answer[276]); $count += $false($answer[282]); $count += $false($answer[283]); $count += $true($answer[284]); $count += $false($answer[285]); $count += $false($answer[296]); $count += $true($answer[304]); $count += $true($answer[306]); $count += $false($answer[313]); $count += $false($answer[314]); $count += $true($answer[332]); $count += $true($answer[333]); $count += $true($answer[335]); $count += $true($answer[354]); $count += $true($answer[360]); return $count; };

$scale_Mfm = function($answer) use($true, $false){ $count = 0; $count += $false($answer[24]); $count += $true($answer[30]); $count += $false($answer[31]); $count += $false($answer[48]); $count += $true($answer[55]); $count += $true($answer[69]); $count += $false($answer[78]); $count += $false($answer[85]); $count += $true($answer[99]); $count += $true($answer[103]); $count += $false($answer[105]); $count += $true($answer[109]); $count += $false($answer[111]); $count += $true($answer[126]); $count += $false($answer[130]); $count += $true($answer[134]); $count += $true($answer[157]); $count += $true($answer[160]); $count += $true($answer[166]); $count += $false($answer[180]); $count += $true($answer[184]); $count += $false($answer[188]); $count += $false($answer[206]); $count += $false($answer[208]); $count += $true($answer[214]); $count += $false($answer[230]); $count += $false($answer[236]); $count += $true($answer[242]); $count += $true($answer[250]); $count += $false($answer[254]); $count += $false($answer[261]); $count += $true($answer[264]); $count += $false($answer[266]); $count += $true($answer[274]); $count += $false($answer[279]); $count += $true($answer[283]); $count += $true($answer[288]); $count += $true($answer[295]); $count += $true($answer[301]); $count += $true($answer[307]); $count += $false($answer[320]); $count += $true($answer[325]); $count += $false($answer[327]); $count += $false($answer[334]); $count += $true($answer[336]); $count += $true($answer[337]); $count += $false($answer[339]); $count += $false($answer[341]); $count += $false($answer[343]); $count += $false($answer[344]); $count += $true($answer[346]); $count += $true($answer[347]); $count += $false($answer[349]); $count += $true($answer[350]); $count += $true($answer[351]); $count += $false($answer[352]); $count += $false($answer[353]); $count += $true($answer[356]); $count += $false($answer[357]); $count += $false($answer[358]); $count += $false($answer[359]); $count += $false($answer[361]); $count += $false($answer[362]); $count += $true($answer[363]); $count += $false($answer[365]); $count += $true($answer[366]); $count += $true($answer[367]); $count += $true($answer[368]); $count += $false($answer[369]); return $count; };

$scale_Pa = function($answer) use($true, $false){ $count = 0; $count += $false($answer[0]); $count += $true($answer[3]); $count += $false($answer[18]); $count += $true($answer[24]); $count += $false($answer[25]); $count += $false($answer[26]); $count += $true($answer[61]); $count += $false($answer[62]); $count += $true($answer[63]); $count += $true($answer[66]); $count += $false($answer[67]); $count += $false($answer[68]); $count += $true($answer[73]); $count += $false($answer[75]); $count += $true($answer[79]); $count += $false($answer[85]); $count += $false($answer[102]); $count += $false($answer[103]); $count += $false($answer[106]); $count += $true($answer[111]); $count += $true($answer[118]); $count += $false($answer[119]); $count += $false($answer[120]); $count += $true($answer[121]); $count += $true($answer[127]); $count += $false($answer[131]); $count += $false($answer[132]); $count += $true($answer[136]); $count += $false($answer[162]); $count += $true($answer[165]); $count += $true($answer[176]); $count += $false($answer[183]); $count += $true($answer[186]); $count += $true($answer[190]); $count += $false($answer[192]); $count += $false($answer[193]); $count += $true($answer[195]); $count += $false($answer[196]); $count += $false($answer[198]); $count += $false($answer[200]); $count += $true($answer[204]); $count += $false($answer[206]); $count += $true($answer[208]); $count += $true($answer[218]); $count += $false($answer[230]); $count += $false($answer[234]); $count += $true($answer[235]); $count += $false($answer[236]); $count += $false($answer[238]); $count += $true($answer[250]); $count += $false($answer[253]); $count += $true($answer[255]); $count += $false($answer[256]); $count += $true($answer[267]); $count += $true($answer[270]); $count += $false($answer[271]); return $count; };

$scale_Pt = function($answer) use($true, $false){ $count = 0; $count += $false($answer[2]); $count += $false($answer[8]); $count += $true($answer[10]); $count += $true($answer[15]); $count += $true($answer[22]); $count += $true($answer[30]); $count += $false($answer[32]); $count += $true($answer[37]); $count += $true($answer[55]); $count += $true($answer[64]); $count += $true($answer[72]); $count += $true($answer[81]); $count += $true($answer[88]); $count += $true($answer[93]); $count += $false($answer[108]); $count += $true($answer[129]); $count += $false($answer[139]); $count += $true($answer[146]); $count += $false($answer[164]); $count += $true($answer[169]); $count += $false($answer[173]); $count += $true($answer[174]); $count += $true($answer[195]); $count += $true($answer[217]); $count += $true($answer[241]); $count += $true($answer[272]); $count += $true($answer[274]); $count += $true($answer[276]); $count += $true($answer[284]); $count += $true($answer[288]); $count += $false($answer[292]); $count += $true($answer[300]); $count += $true($answer[301]); $count += $true($answer[303]); $count += $true($answer[307]); $count += $true($answer[308]); $count += $true($answer[309]); $count += $true($answer[312]); $count += $true($answer[315]); $count += $true($answer[316]); $count += $true($answer[319]); $count += $false($answer[320]); $count += $true($answer[324]); $count += $true($answer[325]); $count += $true($answer[236]); $count += $true($answer[327]); $count += $true($answer[328]); $count += $true($answer[330]); return $count; };

$scale_ANS = function($answer) use($true, $false){ $count = 0; $count += $true($answer[14]); $count += $true($answer[29]); $count += $true($answer[30]); $count += $true($answer[38]); $count += $false($answer[139]); $count += $true($answer[169]); $count += $true($answer[195]); $count += $false($answer[207]); $count += $false($answer[222]); $count += $true($answer[272]); $count += $true($answer[289]); $count += $true($answer[298]); $count += $true($answer[300]); $count += $true($answer[304]); $count += $true($answer[338]); $count += $false($answer[404]); $count += $true($answer[407]); $count += $true($answer[414]); $count += $true($answer[462]); $count += $true($answer[468]); $count += $false($answer[495]); $count += $true($answer[508]); $count += $true($answer[555]); return $count; };

$scale_BAE = function($answer) use($true, $false){ $count = 0; $count += $false($answer[60]); $count += $true($answer[69]); $count += $true($answer[72]); $count += $false($answer[77]); $count += $false($answer[108]); $count += $true($answer[129]); $count += $true($answer[234]); $count += $true($answer[325]); $count += $true($answer[368]); $count += $true($answer[375]); $count += $true($answer[379]); $count += $true($answer[410]); $count += $true($answer[420]); $count += $true($answer[449]); $count += $true($answer[456]); $count += $true($answer[474]); $count += $true($answer[475]); $count += $true($answer[482]); $count += $true($answer[484]); $count += $true($answer[502]); $count += $true($answer[503]); $count += $true($answer[518]); $count += $true($answer[525]); $count += $true($answer[561]); return $count; };

$scale_CIN = function($answer) use($true){ $count = 0; $count += $true($answer[49]); $count += $true($answer[57]); $count += $true($answer[75]); $count += $true($answer[80]); $count += $true($answer[103]); $count += $true($answer[109]); $count += $true($answer[123]); $count += $true($answer[224]); $count += $true($answer[240]); $count += $true($answer[253]); $count += $true($answer[282]); $count += $true($answer[283]); $count += $true($answer[285]); $count += $true($answer[314]); $count += $true($answer[345]); $count += $true($answer[351]); $count += $true($answer[357]); $count += $true($answer[373]); $count += $true($answer[398]); $count += $true($answer[402]); $count += $true($answer[444]); $count += $true($answer[469]); $count += $true($answer[537]); return $count; };

$scale_DEL = function($answer) use($true, $false){ $count = 0; $count += $true($answer[23]); $count += $true($answer[31]); $count += $true($answer[59]); $count += $true($answer[95]); $count += $true($answer[137]); $count += $true($answer[161]); $count += $true($answer[197]); $count += $true($answer[227]); $count += $true($answer[258]); $count += $true($answer[297]); $count += $true($answer[310]); $count += $true($answer[315]); $count += $true($answer[318]); $count += $true($answer[332]); $count += $true($answer[335]); $count += $true($answer[354]); $count += $true($answer[360]); $count += $false($answer[426]); $count += $true($answer[465]); $count += $true($answer[489]); $count += $true($answer[507]); $count += $true($answer[542]); $count += $true($answer[550]); return $count; };

$scale_DEP = function($answer) use($true, $false){ $count = 0; $count += $false($answer[2]); $count += $false($answer[8]); $count += $true($answer[37]); $count += $true($answer[51]); $count += $true($answer[55]); $count += $true($answer[64]); $count += $true($answer[70]); $count += $false($answer[74]); $count += $true($answer[81]); $count += $true($answer[91]); $count += $false($answer[94]); $count += $true($answer[129]); $count += $true($answer[145]); $count += $true($answer[214]); $count += $true($answer[233]); $count += $true($answer[245]); $count += $true($answer[276]); $count += $true($answer[302]); $count += $true($answer[305]); $count += $true($answer[330]); $count += $true($answer[376]); $count += $false($answer[387]); $count += $true($answer[398]); $count += $true($answer[399]); $count += $true($answer[410]); $count += $true($answer[453]); $count += $true($answer[505]); $count += $true($answer[511]); $count += $true($answer[515]); $count += $true($answer[519]); $count += $true($answer[538]); $count += $true($answer[545]); $count += $true($answer[553]); return $count; };

$scale_DTR = function($answer) use($true, $false){ $count = 0; $count += $true($answer[28]); $count += $true($answer[36]); $count += $true($answer[115]); $count += $true($answer[133]); $count += $true($answer[301]); $count += $true($answer[388]); $count += $true($answer[409]); $count += $true($answer[413]); $count += $true($answer[429]); $count += $true($answer[460]); $count += $true($answer[485]); $count += $true($answer[512]); $count += $true($answer[539]); $count += $true($answer[541]); $count += $true($answer[547]); $count += $false($answer[563]); return $count; };

$scale_ENJ = function($answer) use($true, $false){ $count = 0; $count += $false($answer[9]); $count += $true($answer[14]); $count += $true($answer[16]); $count += $true($answer[30]); $count += $true($answer[53]); $count += $true($answer[72]); $count += $true($answer[97]); $count += $false($answer[107]); $count += $true($answer[134]); $count += $true($answer[232]); $count += $true($answer[242]); $count += $true($answer[298]); $count += $true($answer[301]); $count += $false($answer[317]); $count += $true($answer[338]); $count += $true($answer[363]); $count += $true($answer[367]); $count += $true($answer[393]); $count += $true($answer[408]); $count += $true($answer[427]); $count += $true($answer[444]); $count += $true($answer[463]); $count += $true($answer[490]); $count += $true($answer[504]); $count += $true($answer[508]); $count += $true($answer[516]); $count += $false($answer[520]); $count += $true($answer[524]); $count += $true($answer[544]); $count += $true($answer[553]); $count += $true($answer[558]); $count += $false($answer[560]); $count += $true($answer[565]); return $count; };

$scale_FAM = function($answer) use($true, $false){ $count = 0; $count += $true($answer[20]); $count += $true($answer[53]); $count += $false($answer[82]); $count += $false($answer[124]); $count += $true($answer[144]); $count += $true($answer[189]); $count += $true($answer[194]); $count += $true($answer[204]); $count += $false($answer[216]); $count += $true($answer[255]); $count += $true($answer[291]); $count += $true($answer[299]); $count += $true($answer[322]); $count += $true($answer[377]); $count += $true($answer[378]); $count += $true($answer[381]); $count += $false($answer[382]); $count += $true($answer[412]); $count += $true($answer[448]); $count += $false($answer[454]); $count += $true($answer[477]); $count += $true($answer[542]); $count += $true($answer[549]); $count += $true($answer[562]); $count += $true($answer[566]); return $count; };

$scale_ISO = function($answer) use($true, $false){ $count = 0; $count += $true($answer[45]); $count += $false($answer[48]); $count += $false($answer[85]); $count += $true($answer[157]); $count += $true($answer[166]); $count += $true($answer[184]); $count += $false($answer[261]); $count += $true($answer[264]); $count += $true($answer[274]); $count += $false($answer[279]); $count += $true($answer[280]); $count += $false($answer[320]); $count += $true($answer[336]); $count += $false($answer[339]); $count += $true($answer[348]); $count += $false($answer[352]); $count += $false($answer[358]); $count += $false($answer[359]); $count += $false($answer[362]); $count += $true($answer[366]); $count += $false($answer[369]); $count += $true($answer[478]); $count += $true($answer[479]); $count += $true($answer[514]); return $count; };

$scale_MIE = function($answer) use($true, $false){ $count = 0; $count += $false($answer[114]); $count += $true($answer[153]); $count += $false($answer[162]); $count += $false($answer[185]); $count += $true($answer[316]); $count += $true($answer[321]); $count += $true($answer[328]); $count += $true($answer[333]); $count += $false($answer[384]); $count += $true($answer[391]); $count += $true($answer[394]); $count += $true($answer[396]); $count += $false($answer[400]); $count += $true($answer[434]); $count += $true($answer[437]); $count += $true($answer[440]); $count += $true($answer[446]); $count += $false($answer[452]); $count += $true($answer[457]); $count += $false($answer[561]); $count += $true($answer[467]); $count += $true($answer[470]); $count += $true($answer[554]); return $count; };

$scale_OBS = function($answer) use($true){ $count = 0; $count += $true($answer[54]); $count += $true($answer[86]); $count += $true($answer[134]); $count += $true($answer[195]); $count += $true($answer[308]); $count += $true($answer[312]); $count += $true($answer[326]); $count += $true($answer[327]); $count += $true($answer[393]); $count += $true($answer[441]); $count += $true($answer[481]); $count += $true($answer[490]); $count += $true($answer[496]); $count += $true($answer[508]); $count += $true($answer[546]); $count += $true($answer[552]); return $count; };

$scale_PAS = function($answer) use($true, $false){ $count = 0; $count += $true($answer[25]); $count += $true($answer[34]); $count += $true($answer[65]); $count += $true($answer[80]); $count += $true($answer[83]); $count += $true($answer[103]); $count += $true($answer[104]); $count += $true($answer[109]); $count += $true($answer[122]); $count += $true($answer[226]); $count += $true($answer[239]); $count += $true($answer[247]); $count += $true($answer[249]); $count += $true($answer[253]); $count += $false($answer[265]); $count += $true($answer[268]); $count += $true($answer[282]); $count += $true($answer[283]); $count += $true($answer[373]); $count += $true($answer[411]); $count += $true($answer[417]); $count += $true($answer[418]); return $count; };

$scale_PTA = function($answer) use($true){ $count = 0; $count += $true($answer[26]); $count += $true($answer[135]); $count += $true($answer[150]); $count += $true($answer[211]); $count += $true($answer[301]); $count += $true($answer[357]); $count += $true($answer[413]); $count += $true($answer[418]); $count += $true($answer[419]); $count += $true($answer[422]); $count += $true($answer[429]); $count += $true($answer[436]); $count += $true($answer[506]); $count += $true($answer[509]); $count += $true($answer[522]); $count += $true($answer[530]); $count += $true($answer[534]); $count += $true($answer[540]); $count += $true($answer[544]); return $count; };

$scale_RTR = function($answer) use($true, $false){ $count = 0; $count += $true($answer[10]); $count += $true($answer[17]); $count += $false($answer[19]); $count += $true($answer[27]); $count += $false($answer[32]); $count += $true($answer[35]); $count += $true($answer[39]); $count += $true($answer[43]); $count += $false($answer[44]); $count += $false($answer[46]); $count += $true($answer[52]); $count += $false($answer[56]); $count += $true($answer[58]); $count += $false($answer[90]); $count += $true($answer[96]); $count += $true($answer[100]); $count += $true($answer[110]); $count += $false($answer[116]); $count += $false($answer[117]); $count += $false($answer[140]); $count += $false($answer[141]); $count += $true($answer[148]); $count += $false($answer[158]); $count += $false($answer[163]); $count += $true($answer[174]); $count += $false($answer[175]); $count += $false($answer[178]); $count += $false($answer[180]); $count += $false($answer[193]); $count += $false($answer[203]); $count += $false($answer[223]); $count += $true($answer[246]); $count += $false($answer[248]); $count += $false($answer[254]); $count += $false($answer[294]); $count += $false($answer[403]); return $count; };

$scale_SAU = function($answer) use($true, $false){ $count = 0; $count += $true($answer[21]); $count += $true($answer[91]); $count += $true($answer[273]); $count += $true($answer[305]); $count += $true($answer[363]); $count += $true($answer[367]); $count += $true($answer[372]); $count += $true($answer[374]); $count += $true($answer[375]); $count += $true($answer[376]); $count += $true($answer[390]); $count += $true($answer[398]); $count += $true($answer[481]); $count += $true($answer[487]); $count += $true($answer[490]); $count += $false($answer[492]); $count += $false($answer[493]); $count += $true($answer[494]); $count += $true($answer[496]); $count += $true($answer[498]); $count += $true($answer[499]); $count += $false($answer[500]); $count += $true($answer[503]); $count += $true($answer[527]); $count += $true($answer[538]); $count += $true($answer[553]); return $count; };

$scale_A = function($answer) use($true, $false){ $count = 0; $count += $true($answer[30]); $count += $true($answer[37]); $count += $true($answer[55]); $count += $true($answer[64]); $count += $true($answer[81]); $count += $true($answer[126]); $count += $true($answer[134]); $count += $true($answer[214]); $count += $true($answer[232]); $count += $true($answer[242]); $count += $true($answer[250]); $count += $true($answer[272]); $count += $true($answer[276]); $count += $true($answer[288]); $count += $true($answer[300]); $count += $true($answer[308]); $count += $true($answer[309]); $count += $true($answer[310]); $count += $true($answer[324]); $count += $true($answer[327]); $count += $true($answer[337]); $count += $true($answer[338]); $count += $true($answer[340]); $count += $true($answer[346]); $count += $false($answer[387]); $count += $true($answer[389]); $count += $true($answer[390]); $count += $true($answer[393]); $count += $true($answer[399]); $count += $true($answer[407]); $count += $true($answer[410]); $count += $true($answer[414]); $count += $true($answer[420]); $count += $true($answer[427]); $count += $true($answer[441]); $count += $true($answer[447]); $count += $true($answer[450]); $count += $true($answer[463]); $count += $true($answer[468]); return $count; };

$scale_AMAC = function($answer) use($true, $false){ $count = 0; $count += $true($answer[6]); $count += $true($answer[23]); $count += $true($answer[35]); $count += $true($answer[48]); $count += $true($answer[51]); $count += $true($answer[68]); $count += $true($answer[71]); $count += $false($answer[72]); $count += $true($answer[81]); $count += $true($answer[83]); $count += $true($answer[102]); $count += $true($answer[104]); $count += $false($answer[106]); $count += $true($answer[112]); $count += $true($answer[114]); $count += $false($answer[116]); $count += $true($answer[127]); $count += $false($answer[136]); $count += $false($answer[159]); $count += $false($answer[165]); $count += $false($answer[167]); $count += $true($answer[171]); $count += $true($answer[201]); $count += $true($answer[213]); $count += $true($answer[223]); $count += $true($answer[228]); $count += $true($answer[237]); $count += $false($answer[250]); $count += $true($answer[256]); $count += $true($answer[265]); $count += $true($answer[179]); $count += $false($answer[286]); $count += $false($answer[298]); $count += $false($answer[324]); $count += $true($answer[341]); $count += $true($answer[343]); $count += $true($answer[386]); $count += $true($answer[407]); $count += $true($answer[411]); $count += $true($answer[413]); $count += $true($answer[421]); $count += $true($answer[433]); $count += $true($answer[438]); $count += $true($answer[444]); $count += $true($answer[455]); $count += $true($answer[472]); $count += $true($answer[501]); $count += $true($answer[505]); $count += $true($answer[548]); return $count; };

$scale_Do = function($answer) use($true, $false){ $count = 0; $count += $false($answer[30]); $count += $false($answer[51]); $count =+ $true($answer[54]); $count += $false($answer[69]); $count += $false($answer[72]); $count += $false($answer[81]); $count += $false($answer[171]); $count += $false($answer[200]); $count += $false($answer[201]); $count =+ $true($answer[206]); $count += $false($answer[219]); $count += $false($answer[226]); $count =+ $true($answer[231]); $count += $false($answer[242]); $count += $false($answer[243]); $count =+ $true($answer[244]); $count += $false($answer[274]); $count += $false($answer[308]); $count += $false($answer[324]); $count =+ $true($answer[385]); $count += $false($answer[398]); $count += $false($answer[411]); $count =+ $true($answer[415]); $count += $false($answer[469]); $count += $false($answer[472]); return $count; };

$scale_Dpr = function($answer) use($true, $false){ $count = 0; $count += $false($answer[1]); $count += $false($answer[2]); $count += $false($answer[8]); $count += $false($answer[9]); $count += $true($answer[14]); $count += $true($answer[15]); $count += $false($answer[19]); $count += $true($answer[27]); $count += $true($answer[30]); $count += $true($answer[37]); $count += $false($answer[42]); $count += $true($answer[70]); $count += $true($answer[72]); $count += $true($answer[80]); $count += $true($answer[81]); $count += $false($answer[94]); $count += $true($answer[109]); $count += $true($answer[129]); $count += $false($answer[130]); $count += $false($answer[139]); $count += $false($answer[147]); $count += $false($answer[151]); $count += $true($answer[214]); $count += $true($answer[217]); $count += $false($answer[222]); $count += $true($answer[232]); $count += $true($answer[268]); $count += $true($answer[272]); $count += $true($answer[298]); $count += $true($answer[301]); $count += $true($answer[324]); $count += $true($answer[330]); $count += $true($answer[338]); $count += $true($answer[356]); $count += $false($answer[404]); $count += $true($answer[407]); $count += $true($answer[410]); $count += $true($answer[448]); $count += $true($answer[463]); $count += $true($answer[468]); $count += $true($answer[471]); return $count; };

$scale_EPK = function($answer) use($true, $false){ $count = 0; $count += $false($answer[1]); $count += $false($answer[2]); $count += $false($answer[8]); $count += $true($answer[15]); $count += $true($answer[16]); $count += $true($answer[21]); $count += $true($answer[22]); $count += $true($answer[29]); $count += $true($answer[30]); $count += $true($answer[31]); $count += $true($answer[36]); $count += $true($answer[38]); $count += $true($answer[47]); $count += $false($answer[48]); $count += $true($answer[51]); $count += $true($answer[55]); $count += $true($answer[58]); $count += $true($answer[64]); $count += $false($answer[74]); $count += $true($answer[81]); $count += $true($answer[84]); $count += $true($answer[91]); $count += $true($answer[93]); $count += $false($answer[94]); $count += $true($answer[100]); $count += $false($answer[124]); $count += $true($answer[134]); $count += $false($answer[139]); $count += $true($answer[149]); $count += $true($answer[167]); $count += $true($answer[169]); $count += $true($answer[195]); $count += $true($answer[220]); $count += $true($answer[273]); $count += $true($answer[276]); $count += $true($answer[301]); $count += $true($answer[302]); $count += $true($answer[304]); $count += $true($answer[315]); $count += $true($answer[318]); $count += $true($answer[326]); $count += $true($answer[327]); $count += $true($answer[338]); $count += $true($answer[346]); $count += $true($answer[348]); $count += $true($answer[366]); return $count; };

$scale_EPS = function($answer) use($true, $false){ $count = 0; $count += $false($answer[2]); $count += $false($answer[8]); $count += $true($answer[16]); $count += $true($answer[19]); $count += $true($answer[20]); $count += $true($answer[30]); $count += $true($answer[31]); $count += $true($answer[36]); $count += $true($answer[37]); $count += $true($answer[43]); $count += $false($answer[44]); $count += $true($answer[47]); $count += $true($answer[55]); $count += $true($answer[58]); $count += $true($answer[64]); $count += $false($answer[74]); $count += $true($answer[84]); $count += $true($answer[93]); $count += $false($answer[94]); $count += $true($answer[115]); $count += $true($answer[134]); $count += $false($answer[140]); $count += $true($answer[144]); $count += $true($answer[149]); $count += $false($answer[164]); $count += $true($answer[167]); $count += $true($answer[169]); $count += $true($answer[179]); $count += $false($answer[207]); $count += $true($answer[217]); $count += $true($answer[220]); $count += $false($answer[222]); $count += $true($answer[272]); $count += $true($answer[273]); $count += $true($answer[276]); $count += $false($answer[279]); $count += $true($answer[298]); $count += $true($answer[300]); $count += $true($answer[303]); $count += $true($answer[304]); $count += $true($answer[310]); $count += $true($answer[315]); $count += $true($answer[318]); $count += $true($answer[324]); $count += $true($answer[327]); $count += $false($answer[371]); $count += $true($answer[376]); $count += $true($answer[385]); $count += $true($answer[399]); $count += $false($answer[404]); $count += $true($answer[462]); $count += $true($answer[463]); $count += $true($answer[468]); $count += $true($answer[470]); $count += $true($answer[474]); $count += $true($answer[478]); $count += $true($answer[514]); $count += $true($answer[515]); $count += $false($answer[563]); $count += $true($answer[564]); return $count; };

$scale_Fp = function($answer) use($true, $false){ $count = 0; $count += $true($answer[280]); $count += $true($answer[290]); $count += $true($answer[302]); $count += $true($answer[310]); $count += $true($answer[316]); $count += $true($answer[318]); $count += $true($answer[321]); $count += $true($answer[322]); $count += $true($answer[328]); $count += $true($answer[331]); $count += $true($answer[332]); $count += $true($answer[333]); $count += $false($answer[382]); $count += $true($answer[386]); $count += $true($answer[394]); $count += $false($answer[403]); $count += $true($answer[406]); $count += $true($answer[430]); $count += $true($answer[449]); $count += $true($answer[453]); $count += $true($answer[462]); $count += $true($answer[467]); $count += $true($answer[475]); $count += $true($answer[477]); $count += $true($answer[483]); $count += $true($answer[488]); $count += $false($answer[500]); $count += $true($answer[505]); $count += $true($answer[515]); $count += $true($answer[516]); $count += $true($answer[519]); $count += $true($answer[523]); $count += $true($answer[524]); $count += $true($answer[525]); $count += $true($answer[527]); $count += $true($answer[529]); $count += $true($answer[538]); $count += $true($answer[539]); $count += $true($answer[543]); $count += $true($answer[554]); return $count; };

$scale_Fyo = function($answer) use($true, $false){ $count = 0; $count += $true($answer[1]); $count += $false($answer[22]); $count += $false($answer[30]); $count += $false($answer[31]); $count += $true($answer[32]); $count += $false($answer[35]); $count += $false($answer[38]); $count += $true($answer[44]); $count += $false($answer[52]); $count += $false($answer[59]); $count += $false($answer[69]); $count += $false($answer[81]); $count += $false($answer[86]); $count += $true($answer[97]); $count += $false($answer[118]); $count += $false($answer[127]); $count += $true($answer[140]); $count += $true($answer[158]); $count += $true($answer[168]); $count += $false($answer[174]); $count += $true($answer[176]); $count += $true($answer[178]); $count += $true($answer[188]); $count += $false($answer[195]); $count += $true($answer[198]); $count += $true($answer[208]); $count += $true($answer[212]); $count += $false($answer[214]); $count += $false($answer[220]); $count += $false($answer[224]); $count += $false($answer[228]); $count += $true($answer[229]); $count += $false($answer[235]); $count += $true($answer[244]); $count += $false($answer[245]); $count += $false($answer[306]); $count += $false($answer[309]); $count += $false($answer[315]); $count += $true($answer[322]); $count += $false($answer[327]); $count += $true($answer[384]); $count += $false($answer[390]); $count += $false($answer[393]); $count += $true($answer[405]); $count += $true($answer[412]); $count += $true($answer[424]); $count += $false($answer[440]); $count += $false($answer[446]); $count += $false($answer[457]); $count += $false($answer[463]); $count += $false($answer[468]); $count += $false($answer[470]); return $count; };

$scale_GF = function($answer) use($true, $false){ $count = 0; $count += $false($answer[0]); $count += $false($answer[26]); $count += $true($answer[61]); $count += $false($answer[62]); $count += $true($answer[66]); $count += $false($answer[67]); $count += $false($answer[78]); $count += $false($answer[83]); $count += $false($answer[104]); $count += $true($answer[118]); $count += $true($answer[120]); $count += $false($answer[122]); $count += $true($answer[127]); $count += $false($answer[132]); $count += $false($answer[154]); $count += $false($answer[196]); $count += $false($answer[200]); $count += $true($answer[202]); $count += $false($answer[219]); $count += $false($answer[230]); $count += $false($answer[237]); $count += $false($answer[238]); $count += $false($answer[249]); $count += $false($answer[256]); $count += $true($answer[262]); $count += $false($answer[263]); $count += $true($answer[265]); $count += $false($answer[271]); $count += $false($answer[286]); $count += $true($answer[352]); $count += $true($answer[383]); $count += $false($answer[405]); $count += $false($answer[416]); $count += $true($answer[425]); $count += $true($answer[448]); $count += $true($answer[455]); $count += $false($answer[464]); $count += $true($answer[472]); $count += $false($answer[476]); $count += $false($answer[486]); $count += $false($answer[509]); $count += $false($answer[510]); $count += $false($answer[536]); $count += $false($answer[547]); $count += $false($answer[549]); $count += $true($answer[551]); return $count; };

$scale_GM = function($answer) use($true, $false){ $count = 0; $count +=$false($answer[3]); $count += $true($answer[7]); $count += $true($answer[19]); $count +=$false($answer[22]); $count +=$false($answer[43]); $count +=$false($answer[63]); $count +=$false($answer[69]); $count +=$false($answer[72]); $count +=$false($answer[73]); $count +=$false($answer[79]); $count +=$false($answer[99]); $count +=$false($answer[136]); $count += $true($answer[142]); $count +=$false($answer[145]); $count += $true($answer[151]); $count += $true($answer[158]); $count += $true($answer[162]); $count += $true($answer[175]); $count +=$false($answer[186]); $count += $true($answer[198]); $count += $true($answer[213]); $count += $true($answer[236]); $count +=$false($answer[288]); $count += $true($answer[320]); $count +=$false($answer[330]); $count += $true($answer[349]); $count +=$false($answer[350]); $count +=$false($answer[363]); $count += $true($answer[384]); $count += $true($answer[387]); $count +=$false($answer[391]); $count +=$false($answer[394]); $count += $true($answer[400]); $count +=$false($answer[434]); $count +=$false($answer[437]); $count += $true($answer[439]); $count +=$false($answer[440]); $count += $true($answer[461]); $count += $true($answer[466]); $count +=$false($answer[468]); $count +=$false($answer[470]); $count += $true($answer[473]); $count +=$false($answer[497]); $count +=$false($answer[508]); $count +=$false($answer[518]); $count +=$false($answer[531]); $count +=$false($answer[535]); return $count; };

$scale_HR = function($answer) use($true, $false){ $count = 0; $count += $false($answer[0]); $count += $false($answer[14]); $count += $false($answer[28]); $count += $true($answer[66]); $count += $false($answer[68]); $count += $false($answer[76]); $count += $true($answer[78]); $count += $false($answer[88]); $count += $false($answer[97]); $count += $false($answer[115]); $count += $false($answer[116]); $count += $false($answer[128]); $count += $false($answer[152]); $count += $false($answer[168]); $count += $false($answer[170]); $count += $true($answer[206]); $count += $true($answer[285]); $count += $false($answer[292]); $count += $true($answer[304]); $count += $false($answer[343]); $count += $false($answer[389]); $count += $true($answer[397]); $count += $false($answer[399]); $count += $false($answer[419]); $count += $false($answer[432]); $count += $false($answer[439]); $count += $false($answer[459]); $count += $true($answer[470]); return $count; };

$scale_Is1 = function($answer) use($true, $false){ $count = 0; $count += $false($answer[85]); $count += $true($answer[336]); $count += $false($answer[339]); $count += $false($answer[352]); $count += $false($answer[358]); $count += $false($answer[362]); $count += $true($answer[366]); $count += $false($answer[369]); return $count; };

$scale_Is2 = function($answer) use($true, $false){ $count = 0; $count += $false($answer[48]); $count += $true($answer[157]); $count += $true($answer[160]); $count += $true($answer[166]); $count += $true($answer[184]); $count += $true($answer[242]); $count += $false($answer[261]); $count += $true($answer[264]); $count += $true($answer[274]); $count += $false($answer[279]); $count += $true($answer[288]); $count += $false($answer[320]); $count += $false($answer[341]); $count += $false($answer[359]); return $count; };

$scale_Is3 = function($answer) use($false){ $count = 0; $count += $false($answer[0]); $count += $false($answer[6]); $count += $false($answer[9]); $count += $false($answer[13]); $count += $false($answer[36]); $count += $false($answer[44]); $count += $false($answer[68]); $count += $false($answer[111]); $count += $false($answer[117]); $count += $false($answer[119]); $count += $false($answer[127]); $count += $false($answer[133]); $count += $false($answer[141]); $count += $false($answer[167]); $count += $false($answer[177]); $count += $false($answer[188]); $count += $false($answer[196]); $count += $false($answer[198]); $count += $false($answer[247]); $count += $false($answer[254]); $count += $false($answer[255]); $count += $false($answer[296]); $count += $false($answer[329]); $count += $false($answer[345]); $count += $false($answer[349]); $count += $false($answer[352]); $count += $false($answer[353]); $count += $false($answer[358]); $count += $false($answer[362]); $count += $false($answer[364]); $count += $false($answer[421]); $count += $false($answer[422]); $count += $false($answer[429]); $count += $false($answer[431]); $count += $false($answer[448]); $count += $false($answer[455]); $count += $false($answer[464]); return $count; };

$scale_R = function($answer) use($true){ $count = 0; $count += $true($answer[30]); $count += $true($answer[55]); $count += $true($answer[103]); $count += $true($answer[109]); $count += $true($answer[134]); $count += $true($answer[283]); $count += $true($answer[301]); $count += $true($answer[307]); $count += $true($answer[325]); $count += $true($answer[327]); $count += $true($answer[337]); $count += $true($answer[346]); $count += $true($answer[347]); $count += $true($answer[357]); $count += $true($answer[363]); $count += $true($answer[367]); $count += $true($answer[368]); return $count; };

$scale_Rs = function($answer) use($true, $false){ $count = 0; $count =+ $false($answer[6]); $count =+ $false($answer[26]); $count =+ $false($answer[28]); $count =+ $false($answer[31]); $count =+ $false($answer[83]); $count += $true($answer[99]); $count =+ $false($answer[102]); $count =+ $false($answer[104]); $count =+ $false($answer[144]); $count += $true($answer[159]); $count =+ $false($answer[163]); $count =+ $false($answer[168]); $count += $true($answer[198]); $count =+ $false($answer[200]); $count =+ $false($answer[201]); $count =+ $false($answer[234]); $count += $true($answer[265]); $count =+ $false($answer[274]); $count =+ $false($answer[357]); $count =+ $false($answer[411]); $count =+ $false($answer[416]); $count =+ $false($answer[417]); $count =+ $false($answer[429]); $count =+ $false($answer[430]); $count =+ $false($answer[431]); $count += $true($answer[439]); $count =+ $false($answer[455]); $count += $true($answer[466]); $count =+ $false($answer[467]); $count =+ $false($answer[469]); return $count; };

$mf = ($_SESSION['genre'] == 'male') ? $scale_Mfm($_SESSION['answer']) : $scale_Mff($_SESSION['answer']);
$hs = $scale_Hs($_SESSION['answer']);
$k = $scale_K($_SESSION['answer']);
$dp = $scale_Dp($_SESSION['answer']);
$pt = $scale_Pt($_SESSION['answer']);
$es = $scale_Es($_SESSION['answer']);
$ma = $scale_Ma($_SESSION['answer']);

$countB = [
    $scale_L($_SESSION['answer']),
    $scale_F($_SESSION['answer']),
    $k,
    sum5K($hs, $k),
    $scale_D($_SESSION['answer']),
    $scale_Hi($_SESSION['answer']),
    sum4K($dp, $k),
    $mf,
    $scale_Pa($_SESSION['answer']),
    sumK($pt, $k),
    sumK($es, $k),
    sum2K($ma, $k),
    $scale_Is($_SESSION['answer'])
];

$countC = [
    $scale_ANS($_SESSION['answer']),
    $scale_MIE($_SESSION['answer']),
    $scale_OBS($_SESSION['answer']),
    $scale_DEP($_SESSION['answer']),
    $scale_SAU($_SESSION['answer']),
    $scale_DEL($_SESSION['answer']),
    $scale_ENJ($_SESSION['answer']),
    $scale_CIN($_SESSION['answer']),
    $scale_PAS($_SESSION['answer']),
    $scale_PTA($_SESSION['answer']),
    $scale_BAE($_SESSION['answer']),
    $scale_ISO($_SESSION['answer']),
    $scale_FAM($_SESSION['answer']),
    $scale_DTR($_SESSION['answer']),
    $scale_RTR($_SESSION['answer']),
];

$countS = [
    $scale_A($_SESSION['answer']),
    $scale_R($_SESSION['answer']),
    $scale_Fyo($_SESSION['answer']),
    $scale_AMAC($_SESSION['answer']),
    $scale_HR($_SESSION['answer']),
    $scale_Do($_SESSION['answer']),
    $scale_Rs($_SESSION['answer']),
    $scale_Dpr($_SESSION['answer']),
    $scale_GM($_SESSION['answer']),
    $scale_GF($_SESSION['answer']),
    $scale_EPK($_SESSION['answer']),
    $scale_EPS($_SESSION['answer']),
    $scale_Is1($_SESSION['answer']),
    $scale_Is2($_SESSION['answer']),
    $scale_Is3($_SESSION['answer']),
    $scale_Fp($_SESSION['answer'])
];