<?php
session_start();
include_once("scoreMale.php");
include_once("scoreFemale.php");

$sug_D = function($score) { switch($score){ case $score < 41: $text = 'Actividad, entusiasmo, optimismo. Sin disturbios emocionales, ni problemas de inhibición o retracción social. Probabilidad de bajo control de los impulsos. Intereses sociales.'; break; case $score < 56: $text = 'Conformidad, comodidad y adaptación antes las relaciones sociales. Estabilidad emocional, autoconfianza, bajos niveles de depresión y sentimientos de culpa. Relajación, comodidad, felicidad, energía y competividad. Energía elevada para afrontar los problemas y encontrarles solución. Actitud realista.'; break; case $score < 66: $text = 'Probabilidad de inhibición, irritabilidad y timidez. Sentimientos relativamente crónicos de tristeza, infelicidad, insatisfacción consigo mismo y con los demás. Preocupación, pesimismo leve. Actitud responsable. Modestia.'; break; case $score < 76: $text = 'Tendencia al aislamiento, timidez, actitud vergonzante. Nivel energético disminuido, dificultades de concentración. Quejas somáticas, trastornos del sueño. Baja autoestima, sentimientos de inadecuación. Presencia de aflicción, disforia y pesimismo.'; break; default: $text = 'Ensimismamiento, introversión. Desesperanza, sentimientos de culpabilidad. Autopercepción de inadecuación. Preocupación acerca de la muerte; probabilidad de ideación suicida. Apatía, abatimiento, enlentecimiento psicomotor.'; break; } return $text; };

$sug_Dp = function($score) { switch($score){ case $score < 41: $text = 'Rigidez, convencionalismo. Pasividad, escasa asertividad, con bajas expectativas. Sumisión ante reglas y normas sociales o legales. Falta de creatividad y espontaniedad. Moralista, conformista, reservado, autocrítico. Sobrecontrol.'; break; case $score < 56: $text = 'Sinceridad, actitud confiable, confianza hacia los demás. Persistencia, responsabilidad.'; break; case $score < 66: $text = 'Impulsividad. Conducta intrépida y aventurera. Actitud hedonista. Resentimiento, inestabilidad, impaciencia. Sociabilidad. Seguridad y asertividad. Probable creatividad e imaginación.'; break; case $score < 76: $text = 'Baja tolerancia al aburrimiento, al tedio y a la frustración. Problemas con la autoridad. Problemas laborales o matrimoniales recurrentes. Actitud rebelde y hostil, rechazo por las normas sociales y legales. Reacciones emocionales superficiales y de corta duración (vergüenza, culpa). Probabilidad de abuso de sustancias. Antecedentes laborales o escolares de logro reducido. Relaciones y respuestas emocionales superficiales.'; break; default: $text = 'Pobreza en la adecuación del juicio. Inestabilidad, irresponsabilidad. Delegan responsabilidades de sus actos a otros. Actitud centrada en sí mismo, inmadurez. Actitudes y comportamientos antisociales. Agresividad, provocación.'; break; } return $text; };

$sug_Es = function($score) { switch($score){ case $score < 41: $text = 'Convencionalismo, conservadurismo. Control sobre los propios impulsos. Actitud sumisa, dependencia, sensibilidad, bondad, responsabilidad, poca imaginación.'; break; case $score < 56: $text = 'Adaptabilidad. Confiabilidad, seguridad. Equilibrio emocional.'; break; case $score < 66: $text = 'Escaso interés por las personas. Poca habilidad práctica. Creatividad e imaginación. Preocupaciones religiosas o espirituales.'; break; case $score < 76: $text = 'Creencias inusuales. Actos bizarros. Problemas de identificación y autoconfianza. Dificultades de concentración y razonamiento.'; break; default: $text = 'Disturbios del pensamiento. Comportamiento excéntrico. Probabilidad de delirios (somáticos, de persecución, entre otros). Probabilidad de alucinaciones. Retraimiento social, aislamiento. Confusión, desorganización y desorientación. Objetivos indeterminados, inalcanzables o exagerados. Ansiedad generalizada y con aguda agitación psicológica. Presenta apatía, impulsividad, hostilidad, desordenamiento, resentimiento, incomprensión, inadaptación, excentricidad, nerviosismo, prolijidad. Contacto con la realidad deficitario.'; break; } return $text; };

$sug_F = function($score) { switch($score){ case $score < 50: $text = 'Libre de tensión. Respuestas razonables. Conformismo y conformidad social. Convencionalismo. Probabilidad de fingir para proyectar una imagen aceptable. Negación de dificultades personales. Descarte de psicopatología severa.'; break; case $score < 66: $text = 'Respuesta hacia un área de conflicto particular. Posibilidad de ser una persona neurótica. Adaptabiliad y buen funcionamiento en aspectos divergidos a las áreas de conflicto.'; break; case $score < 80: $text = 'Rigidez en convicciones morales, sociales y/o políticas. Trastorno neurótico o psicótico. Una vez descartado un trastorno psiquiátrico puede tratarse de una persona oportunista, depresiva, impaciente, insatisfecha, inestable y/o curiosa'; break; case $score < 100: $text = 'Responder a todos los reactivos falso. Simulación o exageración de síntomas. Resistencia a la prueba. Falta de cooperación. Psicosis.'; break; default: $text = 'Respuestas ejecutadas al azar o por incapacidad para comprender la lectura. Puede haber respondido verdadero o falso a todos los reactivos. Simulación de enfermedad mental o exageración de la misma. Paciente psiquiátrico seriamente perturbado. Inconformismo o resignación ante creencias y/o costumbres políticas, sociales o religiosas.'; break; } return $text; };

$sug_Hi = function($score) { switch($score){ case $score < 41: $text = 'Probabilidad de actitud cínica. Poco interesado en las relaciones sociales, conformista, tendencias de aislamiento social. Gama de intereses restringida. Obstinado, poco amistoso y evita situaciones donde él sea el líder. Conformista, con pocas metas. Poco preocupado por su salud, no manifiesta síntomas somáticos. Frío, distante, realista, poco arriesgado.'; break; case $score < 56: $text = 'Actitud realista. Apertura hacia los sentimientos. Estilo lógico y racional.'; break; case $score < 66: $text = 'Actitud centrada en sí mismo, superficialidad. Inmadurez y actitud manipuladora ocasional. Conformismo, moralismo. Necesidad de agradar, inseguridad. Actitud demostrativa y extravertida.'; break; case $score < 76: $text = 'Predominio defensivo de negación y disociación. Quejas y síntomas somáticos específicos. Ingenuidad, escasa capacidad de insight. Actitud exigente, demandante e histriónica.'; break; default: $text = 'Alta sugestionabilidad. Tendencia a la preocupación. Utiliza técnicas manipuladoras, tortuosas para obtener atención y simpatía. Episodios súbitos de ansiedad o pánico. Desinhibición, inseguridad, conducta arrebatada e infantil. Aparición de síntomas físicos como reacción a situaciones o actitudes vergonzantes. Manifiesta preocupación ante el fracaso escolar o laboral aunque suelen ser muy poco trabajador y con pocas aspiraciones. Le cuesta comprender los orígenes de su propio comportamiento. No manifiesta síntomas depresivos. Se involucran emocionalmente, son amistosos y conversadores. Da más de sí de acuerdo a sus intereses personales.'; break; } return $text; };

$sug_Hs = function($score) { switch($score){ case $score < 41: $text = 'No presenta quejas o preocupaciones somáticas. Probabilidad de desatención a signos síntomas de enfermedad. Optimismo, energía, satisfacción. Efectividad.'; break; case $score < 56: $text = 'Escasa preocupación acerca del cuerpo y la salud propia. Emotividad abierta y equilibrada. Realista y perspicaz.'; break; case $score < 66: $text = 'Presencia de un trastorno de salud específico. Probabilidad de inmadurez, irritabilidad, tendencia a la queja y al lamento. Preocupación por la salud corporal propia (peso, funcionamiento físico, entre otras).'; break; case $score < 76: $text = 'Reacción exagerada a cualquier problema real. Egoísmo, extremo centramiento en sí. Actitudes derrotistas y pesimistas. Amargura y perspectiva cínica. Demanda constante de atención. Exageración de los problemas físicos. Quejas intensas y temperamento mudable.'; break; default: $text = 'Delirios somáticos o concernientes al cuerpo. Múltiples síntomas y quejas, probablemente constricción.'; break; } return $text; };

$sug_Is = function($score) { switch($score){ case $score < 41: $text = 'Calidez. Sociabilidad, actitud agregaria, carismáticos. Autoconfianza y asertividad. Autoindulgencia. Exhibicionismo, iniciativa, manipulador, oportunista, inmaduro.'; break; case $score < 56: $text = 'Actividad, energía. Actitud amistosa. Locuacidad.'; break; case $score < 66: $text = 'Reserva, seriedad, cautela. Sobrecontrol de los impulsos. Apocada habilidad social.'; break; case $score < 76: $text = 'Introversión. Depresión. Actitud vergonzante, timidez. Falta de autoconfianza. Actitud taciturna, irritabilidad. Rigidez en sus convicciones, sumisión, obediencia.'; break; default: $text = 'Ensimismamiento, actitud distante. Desconfianza, inseguridad, indecisión. Austeridad, recato. Rumiación.'; break; } return $text; };

$sug_K = function($score) { switch($score){ case $score < 41: $text = 'Se respondió verdadero a la mayoría de reactivos. Desorganización emocional, ingenuidad, autocrítica, debilidad yoica. Pretende proyetar una imagen inaceptable de su persona. Exageración de conflictos. Timidez, inhibición, incapacidad de relacionarse con los demás. Sincero y torpe en sus relaciones, cínico o incrédulo. Conformista. Abulia. Desconfianza, suspicacia de los demás. Dificultad para enfrentar los problemas o darles solución. Confusión orgánica o psicótica. Niveles bajos de autoconocimiento y autocomprensión.'; break; case $score < 71: $text = 'Adaptación, sociabilidad, capacidad intelectual alta. Independencia, autoconfianza. Alto nivel de comunicación con el medio. Comprensión y solución de problemas de forma independiente y razonable. Ingenio y versatilidad. Elevado control en sus relaciones interpersonales. Pensamiento claro. Pocos síntomas de trastorno emocional.'; break; default: $text = 'Posible negación de problemas personales. Respondió falso a gran parte de los reactivos. Pretende dar una imagen de control y eficacia. Timidez, indecisión, inhibición. Falta de autoconocimiento y autoentendimiento. Intolerancia a convicciones exrtañas o poco convencionales. Baja probabilidad de conductas antisociales.'; break; } return $text; };

$sug_L = function($score) { switch($score){ case $score < 41: $text = 'Actitud pesimista y apática. Frecuente aparición de fatiga. Depresión. Falta de energía. Timidez, dependencia. Poca autoconfianza. Humildad, modestia. Indiferencia y poco afán antes cosas o situaciones que se presentan. Sentimientos depresivos.'; break; case $score < 56: $text = 'Sociabilidad, amigabilidad. Actitud responsable, realista. Entusiasmo. Equilibrio'; break; case $score < 66: $text = 'Gregario. Poca tolerancia al tedio. Amplia gama de intereses. Contracción al trabajo, efectividad. Orientación al logro. Actitud emprendedora.'; break; case $score < 76: $text = 'Euforia. Actividad excesiva. Locuacidad. Inquietud, impaciencia, labilidad. Relaciones superficiales.'; break; default: $text = 'Expansividad, grandiosidad. Personas activas y enérgicas. Pobre control impulsivo. Hiperactividad, excitación, distractibilidad, irritabilidad, hostilidad injustificada e irracional, agitación, rapidez psicomotora, poca tolerancia a la frustración. Toma de decisiones impulsiva. Confusión.'; break; } return $text; };

$sug_Ma = function($score) { switch($score){ case $score < 41: $text = 'Pasiva, sumisa, restringida, dependencia, modestia. Buen control de impulsos. Facilidad de autocomprenderse y para obeservar errores externos de sí misma.'; break; case $score < 52: $text = 'Empatía. Conducta competente. Iniciativa. Actitud de consideración. Idealismo.'; break; case $score < 60: $text = 'Actividad. Actitud aventurera. Espontaniedad. Asertividad.'; break; case $score < 70: $text = 'Autoconfianza, equilibrio, estabilidad, seguridad y vigor. Estilo lógico, poco emocional. Competitividad.'; break; default: $text = 'Agresividad y deshinibidas. Rebeldía contra roles típicamente femeninos. Dominantes y dadas de acción. Poca dependencia. Poco amigables, torpes y varoniles. Suele intensificarse el significado si la escala 4 es también elevada.'; break; } return $text; };

$sug_Mff = function($score) { switch($score){ case $score < 50: $text = 'Presenta sinceridad, autocrítica, confianza. Capacidad de liderazgo, seguridad, independencia, espontaniedad, autonomia. Sarcástico, irónico, cínico.'; break; case $score < 70: $text = 'Conforme con la imagen del sí. Conformismo social. Moralismo y rigidez.'; break; default: $text = 'Estado confuncional. Escasa capacidad introspectiva. Resistencia a la evaluacion. Moralismo y rigidez excesivo. Estilo represivo. Baja tolerancia a la frustración, estrés, presiones ciscunstanciales. Ingenuidad y falta de perspicacia.'; break; } return $text; };

$sug_Mfm = function($score) { switch($score){ case $score < 41: $text = 'Patrón tradicional de intereses masculinos. Pocos intereses, temerarios, descuidados, toscos, poca originalidad, agresivos. Orientado a la acción. Si la escala 4 es elevada, puede reflejar un estereotipo de machismo prominente.'; break; case $score < 56: $text = 'Sentido práctico. Actitud realista. Convencionalismo. Iniciativa.'; break; case $score < 66: $text = 'Control del sí. Expresividad demostrativa. Sentido común. Intereses hacia el arte, la estética y la belleza. Tacto y sensibilidad social.'; break; case $score < 76: $text = 'Curiosidad y creatividad. Actitud de tolerancia. Ambicioso, constante en sus metas, competitivo, individualismo. Intereses intelectuales. Empatía.'; break; default: $text = 'Suave, extremadamente pasivo y sumiso. Homosexualidad manifiesta o reprimida. Posibilidad de conflictos de identidad sexual mayor.'; break; } return $text; };

$sug_Pa = function($score) { switch($score){ case $score < 41: $text = 'Pacientes no psiquiátricos: Tendencia al equilibrio y al ánimo placentero. Sujetos ordenados, razonables, maduros en sus relaciones, prudentes. Lealtad, confianza. Reservado, convencional, autocontrol. Interesado en actividades sociales. Adaptación a situaciones cotidianas. Ordenados, sensatos, organizados y cautelosos. Pacientes clínicos: Prudente, evasivo, reservado, desconfiado, obstinado, testarudo. Falta de interés. Insatisfacción, sensible, egocéntrico, convicciones rígidas, poco exitoso. Torpe, descortés, rudo. Susceptible. Poca capacidad de insight. Probabilidad de rasgos paranoides.'; break; case $score < 56: $text = 'Racionalidad. Pensamiento claro. Cautela. Flexibilidad.'; break; case $score < 66: $text = 'Sensibilidad al rechazo y a los desaires. Notorio interés por las opiniones ajenas. Sujetos enérgicos, trabajadores, creativos, inteligentes, colaboradores. Falta de autoconfianza. Nerviosismo y preocupación. Desconfianza. Cautela y defensa en el inicio de los contactos sociales. Contracción al trabajo.'; break; case $score < 76: $text = 'Ira, resentimiento, sensibilidad, desconfianza, suceptibilidad. Tendencias paranoides. Desplazamiento de la culpa, actitud crítica. Hostilidad, suspicacia. Moralidad, rigidez en convicciones, obstinación. Tendencia a racionalizar y/o negar conflictos emocionales. Tendencia a malinterpretar situaciones sociales.'; break; default: $text = 'Probabilidad de desorden del pensamiento. Sintomas psicóticos. Proyección como mecanismo de defensa. Pensamientos perturbados, delirios de grandenza. Creencias erróneas. Ideas de referencia. Disposición vengativa, hostilidad, rencor y amargura. Cavilación excesiva. Probabilidad de actuación en función del delirio.'; break; } return $text; };

$sug_Pt = function($score) { switch($score){ case $score < 41: $text = 'Autoconfianza, metas e intereses variados. Libre de inseguridad. Ausencia de temores desadaptativos. Actitud relajada y de bienestar. Persistencia y eficiencia.'; break; case $score < 56: $text = 'Actitud confiable. Equilibrio, adaptabilidad, capaces, eficientes sin preocupaciones innecesarias. Organización, puntualidad.'; break; case $score < 66: $text = 'Conciencia y responsabilidad acerca del propio accionar. Tendencia a intelectualizar. Contracción al trabajo. Organización, orden, tendencia al perfeccionismo. Actitud autocrítica. Capacidad introspectiva.'; break; case $score < 76: $text = 'Inseguridad, ansiedad, tensión. Preocupación, actitud aprensiva, nerviosismo, agitación, angustia. Temor a cometer equivocaciones y errores.\n Minuciosidad, indecisión. Labilidad de intereses Moralismo'; break; default: $text = 'Cavilación, rumiación permanente de problemas y sus posibles soluciones. Agitación psicomotora. Sentimientos de culpa, ansiedad, miedo irracional, temores. Probabilidad de conductas rituales.\n Supersticiones, rigidez en convicciones religiosas o morales. Sentimientos de culpa. Expresiones de depresión.'; break; } return $text; };

$sug_ANS = function($score){ switch($score){ case $score > 64: $text = 'Los adolescentes con puntuaciones altas indican síntomas de ansiedad, incluyendo tensión preocupaciones frecuentes, trastornos del sueño (por ejemplo pesadillas, sueño intranquilo y dificultad para conciliar el sueño). Indican también confusión, problemas para concentrarse e incapacidad para mantenerse ocupados en una tarea. Perciben que la vida es difícil para ellos y creen que sus dificultades son insuperables. Los adolescentes con calificaciones altas en esta escala se preocupan porque consideran que pueden volverse locos y sienten que un suceso terrible está a punto de ocurrir. Parecen darse cuenta de sus problemas y de que son diferentes a otros adolescentes. Posible existencia de relaciones conflictivas con los padres. El adolescente tiene conciencia de las preocupaciones, generalmente acompañada de la sensación subjetiva de no poder superarlas. Esta escala parece evaluar la desadaptación general, como síntomas específicos tales como la depresión y los problemas somáticos'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_BAE = function($score){ switch($score){ case $score > 64: $text = 'Las personas con puntajes elevados en esta escala tienen una opinión muy pobre de ellas mismas. Creen que no les agradan a los demás y que no son importantes para otros. Mantienen actitudes negativas hacia sí mismos, incluyendo pensamientos como el no ser atractivos, considerados torpes, incapaces e inútiles y percibirse como una carga para los demás. Tienen poca confianza en sí mismos y encuentran difícil aceptar cumplidos de otros, se sienten abrumados por los defectos que ven en su persona. Se comportan en forma desfavorable con los demás y tienden a ser pasivos en sus relaciones interpersonales. Los cónyuges de estos individuos los describen como personas que se dan por vencidas con facilidad, susceptibles al rechazo y con poca confianza en sí mismos. Son personas que experimentan dificultad para tomar decisiones, se preocupan demasiado y tienen miedo a muchas cosas.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_CIN = function($score){ switch($score){ case $score > 64: $text = 'En personas con puntajes altos en esta escala manifiestan ideas misantrópicas; suponen motivaciones ocultas y negativas detrás de las acciones de los demás, quizá crean, por ejemplo, que la mayor parte de la gente es honesta solo por miedo a ser descubierta. Creen que los demás no son confiables, debido a que se utilizan unos a otros y son amigables solo por razones egoístas. Posiblemente mantengan actitudes negativas hacia personas cercanas, incluyendo compañeros de trabajo, familiares y amigos: en general son poco amigables y no ayudan a los otros. Algunas de estas personas tienen poca motivación de logro. Si las puntuaciones son muy elevadas tal vez se observan ideas de tipo paranoide. En estudios realizados en delincuentes se encontró esta escala elevada, siendo el grupo de homicidas el que presento las calificaciones más altas.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_DEL = function($score){ switch($score){ case $score > 64: $text = 'Los pensamientos delirantes que se manifiestan en las personas con puntuaciones elevadas son característicos de proceso psicótico de pensamiento. Quizá manifiesten alucinaciones auditivas, visuales u olfativas, además de reconocer que los pensamientos propios son extraños y peculiares. Implica también ideas paranoides. Estas personas pueden creer que tienen una misión o poderes especiales. En la población mexicana indica que esta elevación puede deberse a factores religiosos y místicos.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_DEP = function($score){ switch($score){ case $score > 64: $text = 'Pensamientos depresivos significativos; además, quizá involucran sentimientos de tristeza, incertidumbre acerca del futuro y desinterés por la propia vida. Los individuos que puntúan alto en DEP tienden a la cavilación, manifiestan infelicidad, lloran fácilmente y expresan sentimientos de desesperanza y vacío interior. Quizá verbalicen ideas suicidas o deseos de morir; pueden llegar a creer que están condenados o que han cometido pecados imperdonables. Perciben a las demás personas como carentes de interés en ellos o incapaces de apoyarlos. Mientas más alta es la puntuación más acentuadas las características depresivas de la persona. A los hombres con puntuaciones altas, se les consideraba como faltos de energía y desinterés en las cosas. Además de sensibles al rechazo, indecisos y poco efectivos para enfrentar los retos cotidianos.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_DTR = function($score){ switch($score){ case $score > 64: $text = 'Las puntuaciones elevadas en esta escala indican conductas o actitudes que provocan un desempeño laboral pobre. Algunos de los problemas de estas personas se relacionan con poca confianza en sí mismos, falta de concentración, obsesividad y tensión, así como dificultad para tomar decisiones. Otros se refieren a falta de apoyo familiar en la elección de su carrera, cuestionamientos personales sobre esta elección, y actitudes negativas hacia compañeros de trabajo. Algunas de estas personas manifiestan ansiedad y preocupación excesiva, otras refieren síntomas depresivos. Los rasgos más sobresalientes de sus parejas adjudicaron a las personas que obtenían calificaciones elevadas en DTR, fueron desadaptación generalizada: los percibían como poco amigables y cooperadores, además de distantes de los otros. En selección de personal, las personas con puntuaciones elevadas, tienen dificultades de adaptación en el trabajo. Lo anterior ocurre aunque la escala no esté marcadamente elevada, pero sí que sea el pico del perfil.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_ENJ = function($score){ switch($score){ case $score > 64: $text = 'Las personas con puntajes altos en esta escala presentan problemas de control del enojo, se consideran a si mismas como irritables y gruñonas, además de impacientes, temperamentales y tercas. A veces sienten deseos de maldecir o destrozar cosas. Pueden perder el autocontrol y dañar fisicamente a la gente o a objetos. Mientras más alta la escala más probabilidades de que se muestre abiertamente agresiva. Los hombres fueron descritos por sus parejas como desagradables, tercos, con problemas en sus relaciones interpersonales, enojonas y con arrebatos agresivos. Las mujeres presentaban estas mismas características, pero además se entristecían fácilmente y se les dificultaba salir de ese estado.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_FAM = function($score){ switch($score){ case $score > 64: $text = 'Los individuos con puntuaciones elevadas en FAM, manifiestan desavenencias y pleitos desagradables y poco afectuosos. Incluso quizá sientan odio por su familia. Recuerdan haber sufrido abusos en su infancia y consideran sus matrimonios como infelices y faltos de afecto. Probablemente tengan historias de abuso físico. Los varones con puntajes altos fueron descritos por sus parejas como desadaptados, hostiles y antisociales, en tanto que las mujeres eran percibidas como desadaptadas, hostiles, hiperactivas, antisociales y poco confiables o responsables.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_ISO = function($score){ switch($score){ case $score > 64: $text = 'Evalúa la presencia de miedos específicos, que incluyen ver sangre, estar en lugares altos, temor a dejar el hogar, a desastres naturales, etc. Las mujeres muestran calificaciones más elevadas que los hombres. También se eleva en reclusos probablemente por miedo específico a ser castigado. Las mujeres que calificaron alto, fueron vistas por sus parejas como: desadaptadas, nerviosas y preocupadas acerca de la muerte.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_MIE = function($score){ switch($score){ case $score > 64: $text = 'A los individuos con puntajes altos les cuesta trabajo relacionarse con los demás y prefieren estar solos. Es probable que en situaciones sociales se sientan aislados y poco integrados al grupo. Se consideran a sí mismos como tímidos y no les agradan las fiestas u otras reuniones sociales. Algunos tienen perturbaciones de sueño y preocupaciones con respecto a la salud. Algunos se les diagnostican frecuentemente con desórdenes depresivos. Algunos fueron descritos por su pareja como tímidas, tranquilas, poco amigables e incapaces de disfrutar de las fiestas y de la convivencia con los amigos. '; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_OBS = function($score){ switch($score){ case $score > 64: $text = 'Las personas con puntuaciones elevadas en esta escala son muy trabajadoras, activas y orientadas hacia el trabajo: frecuentemente se muestran impacientes, irritables y tensas. Para ellos, no hay suficiente tiempo en el día para terminar sus tareas, por lo que no les gusta esperar y ser interrumpidos. Son muy directos y pueden ser desagradables en sus relaciones con otros, a quienes presionan mediante su agresividad. Suelen ser hostiles y se enojan con facilidad. Al parecer en mujeres esta es una medida de desadaptación, quienes obtienen puntajes altos son consideradas como suspicaces. Se refieren a expresiones de enojo y competencia. Las esposas de los hombres que obtuvieron puntuaciones elevadas, los describen como mundanos, críticos, enojones y tensos.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_PAS = function($score){ switch($score){ case $score > 64: $text = 'Dificultades para tomar decisiones y meditan excesivamente acerca de sus asuntos o problemas, provocando que otros se impacienten. Tener que llevar a cabo cambios los llena de tensión y pueden manifestarse algunas conductas compulsivas, como contar o guardar cosas sin importancia. Tienden a preocuparse en exceso lo que con frecuencia puede llevarlos a sentirse abrumados por sus propios pensamientos. Los hombres que calificaron alto fueron descritos por sus parejas como: desinteresados en las cosas y faltos de confianza en sí mismos. Las mujeres fueron descritas como realistas acerca de sus habilidades, exageradamente autocríticas y con tendencia a culparse a sí mismas.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_PTA = function($score){ switch($score){ case $score > 64: $text = 'Puntajes elevados indican actitudes misantrópicas similares a CIN, problemas de conducta durante los años escolares y prácticas antisociales como robar o hurtar en supermercados, lo que puede dar lugar a problemas con la ley. Las personas que tienen puntuaciones altas en esta escala manifiestan disfrutar con las artimañas de los criminales y aunque no incurran en conducta ilegal, creen que no está mal evitar el incumplimiento de la ley, son poco confiables y deshonestos. Tanto hombre y mujeres fueron descritos por sus parejas como personas que habían incurrido en prácticas antisociales. Los varones fueron descritos como muy demandantes, inmaduros, abusaban de substancias y habían tenido problemas con la ley. Las mujeres fueron descritas como mentirosas, amenazantes con quienes discreparan de sus opiniones, poco constructivas, no dispuestas a recibir ayuda y con poca claridad de juicio. En selección de personal se tiene que tomar en cuenta que las personas con puntuaciones altas se les consideran no confiables y tienen dificultades para aceptar reglas, aun cuando no esté elevada, pero sea un pico del perfil.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_RTR = function($score){ switch($score){ case $score > 64: $text = 'Manifiestan actitudes negativas hacia los médicos y al tratamiento de salud mental. No creen que alguien pueda comprenderlos ni ayudarlos. Les resulta muy incómodo tratar con alguien más sus asuntos o problemas personales. Quizá deseen que todo permanezca igual en su vida y probablemente crean que un cambio es imposible. Prefieren pasar por alto una crisis o dificultad que enfrentarla; con frecuencia reportan sintomas somáticos.'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_SAU = function($score){ switch($score){ case $score > 64: $text = 'Puntajes altos se presentan en personas con síntomas físicos en diversos órganos corporales. Se incluyen sintomas gastrointestinales (estreñimiento, náuseas y vómitos, problemas estomacales, etc.) problemas neurológicos (convulsiones, mareos, desmayos y parálisis) problemas en la piel, dolor (cabeza, rodillas), problemas respiratorios (tos, fiebre de heno o asma) estos individuos se preocupan por su salud y se sienten más enfermos que el resto de las personas. Las personas que tienen problemas reales de salud puntuan elevadas en esta escala'; break; case $score <= 64: $text = 'Puntuación normal'; break; } return $text; };

$sug_A = function($score){ switch($score){ case $score < 41: $text = "Es indicativa de que el individuo no se siente ansioso, con fluidez verbal, franca, abierta amistosa, sociable, amable, informal, asume un papel preponderante en la relación con los demás. Es persuasivo, exhibicionista y eficiente, capaz de expresar ideas claras, versátil ingeniosos, confiado en sí mismo, competitivo con un alto valor del éxito y logros intensado en el poder, la posición y el reconocimiento.<br> Por otra parte manipula a las demás persona, y es incapaz de demorar la satisfacción de sus impulsos, generalmente actúa antes de reflexionar, sin considerar las consecuencias de sus actos. Además los puntajes bajos reflejan ausencia de angustia emocional. Estas personas tienden a ser enérgicas, competitivas y socialmente extrovertidas. Pueden ser incapaces de tolerar la frustración y usualmente prefieren la acción a la reflexión."; break; case $score < 64: $text = "Son personas que se caracterizan por sentirse ansiosas e incomodas, son pesimistas y apáticas. Generalmente se alejan de personas que los rodean, debido a que son temerosas y les falta confianza en sus capacidades; tienden a ser cautelosas, y dudan para tomar decisiones, se dejan influir pos sentimientos personales difusos, además se inclinan a racionalizar acerca de sus dificultades, y llegan a lastimar a otros. Son personas sumisas complacientes, sugestionables y conformistas, por lo que aceptan de manera abierta la autoridad de otros."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_AMAC = function($score){ switch($score){ case $score < 41: $text = "Los puntajes bajos indican que el individuo tiende a ser introvertido, tímido y con falta de confianza en sí mismo. Puntajes crudos menores de 24 contraindican abuso de substancias."; break; case $score > 64: $text = "La elevación de la escala Mac Andrew no sugiere desarrollo de adicción a las substancias ni indica la presencia de uso o abuso de substancias, solamente sugiere un desarrollo potencial de alcoholismo o posibles problemas de abuso de drogas. Los puntajes altos son característicos también de individuos que son socialmente extrovertidos y que están dispuestos a correr riesgos, además tienen problemas para concentrarse, pueden tener historias de problemas de conducta en la escuela o con la ley y disfrutan las competencias de cualquier tipo. Los puntajes naturales arriba de 24 sugieren abuso de substancias, ya sea alcohol u otras drogas."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_Do = function($score){ switch($score){ case $score < 41: $text = "Las puntuaciones bajas en Do, muestran a personas sumisas, poco enérgicas y fácilmente influenciables por otras personas, carecen de confianza en sí mismas y sienten que manejan sus problemas inadecuadamente."; break; case $score > 64: $text = "Los puntajes altos de Do son asociados con equilibrio, confianza, liderazgo, seguridad en sí mismo, iniciativa social, perseverancia, resolución y liderazgo de grupo, es decir, son características de personas consideradas generalmente como dominantes en situaciones sociales, que se consideran a sí mismos y son considerados por los demás capaces de enfrentar apropiadamente las situaciones personales, no se intimidan fácilmente y se sienten seguros. Suelen ser personas optimistas, eficientes, realistas y orientadas a las tareas que les son encomendadas, por lo que se muestran muy perseverantes y ecuánimes ante situaciones adversas."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_Dpr = function($score){ switch($score){ case $score < 41: $text = "Los sujetos con puntuaciones bajas en Dpr, tienden a ser bien adaptados, optimistas y consientes."; break; case $score > 64: $text = "Parecen estar un poco adaptadas, además de ser generalmente ineficientes, pesimistas y angustiados además pueden desarrollar síntomas físicos durante periodos de mayor estrés y sentir que la vida los abruma la mayor parte del tiempo"; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_EPK = function($score){ switch($score){ case $score > 64: $text = "Los veteranos de guerra y otras personas que hayan experimentado un evento catastrófico y que obtengan puntuaciones altas en EPK, tienden a presentar síntomas de trastorno por estrés postraumático, que incluyen angustia emocional intensa, así como ansiedad y alteraciones del sueño, sienten culpa y depresión pos sus experiencias, presentan desordenes emocionales y manifiestan tener pensamientos intrusitos no deseados, además sienten que han perdido el control sobre sus emociones y pensamientos, expresan sentimientos de no ser comprendidos o considerados por los demás, debido a las situaciones estresantes que han vivido."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_EPS = function($score){ switch($score){ case $score < 89: $text = "Si tanto la F como la Fp están debajo de 89 se puede interpretar todas las escalas, las básicas, las de contenido y las suplementarias."; break; case $score > 90: $text = "Puntuacion cuestionable No se deben interpretar las escalas de contenido y las suplementarias."; break; case 110: $text ="Utilidad del perfil invalida Posible patologia, si otras escalas relacionadas son validas. Si la F es valida pero la Fp no, solo se podrá interpretar las escalas basicas, pero no las suplementarias."; break; case $score > 110: $text = "Puntuacion invalida Si la F y la Fp están arriba de 110, la prueba no es valida y NO se interpreta."; break; } return $text; };

$sug_Fp = function($score){ switch($score){ case $score < 41: $text = "Las personas con puntajes bajos tienden a presentar más problemas y más severos que las demás personas. Además tienen pocos recursos psicológicos para enfrentarse al estrés, por lo que su pronóstico con relación al cambio en psicoterapia, no es positivo."; break; case $score > 64: $text = "Tienden a estar más adaptados psicológicamente y muestran más habilidades para enfrentarse a los problemas y situaciones estresantes. Tienden a ser más estables y responsables en sus actividades, lo cual los hace confiables ante los demás; además son persistentes, inteligentes, e independientes, por lo que producen una primera impresión favorable en quienes los rodean. Sin embargo, pueden llegar a ser oportunistas y manipuladores para lograr sus objetivos, debido a que desarrollan fuertes intereses y se muestran competitivos. Asimismo, quizá sean hostiles y rebeldes hacia la autoridad, especialmente por su gran confianza en sí mismos, de modo que llegan a ser sarcásticos y cínicos ante los demás. Los hombres con puntuaciones elevadas tienen un apropiado estilo de conducta masculino."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_Fyo = function($score){ switch($score){ case $score > 64: $text = "Parece estar muy relacionada con los índices de ansiedad y con la Pt y A. La escala EPS tiende a elevarse en personas que presentan trastornos somáticos en los que la ansiedad es un componente importante. Se encontró muy elevada en pacientes con colon irritable y también en pacientes con dermatitis, lo que podría indicar que tiende a elevarse en personas que presentan trastornos somáticos en los que la ansiedad es un componente importante."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_GF = function($score){ switch($score){ case $score < 41: $text = "Puntuación baja"; break; case $score > 64: $text = "Las puntuaciones elevadas tanto en hombres con mujeres, son características positivas, debido a que son personas que tienden a tener confianzas en sí mismas y libres de temores y preocupaciones. En caso de varones GM se relaciona con una gran confianza en sí mismos, gran perseverancia y amplios intereses, además de la carencia de temores o sentimientos referentes de sí mismos. Para las mujeres GM se vincula con una gran confianza en sí mismas, con honestidad y la disposición para probar nuevas cosas, además de que indica la carencia de preocupaciones y sentimientos referidos a sí mismas."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_GM = function($score){ switch($score){ case $score < 41: $text = "Puntuación baja"; break; case $score > 64: $text = "Las puntuaciones elevadas tanto en hombres con mujeres, son características positivas, debido a que son personas que tienden a tener confianzas en sí mismas y libres de temores y preocupaciones. En caso de varones GM se relaciona con una gran confianza en sí mismos, gran perseverancia y amplios intereses, además de la carencia de temores o sentimientos referentes de sí mismos. Para las mujeres GM se vincula con una gran confianza en sí mismas, con honestidad y la disposición para probar nuevas cosas, además de que indica la carencia de preocupaciones y sentimientos referidos a sí mismas."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_HR = function($score){ switch($score){ case $score < 41: $text = "Puntuaciones bajas en HR, no existen suficientes datos que permitan la interpretación adecuada, por lo que dichas puntuaciones pueden interpretarse de dos formas, ya que no se espera que presenten el síndrome de hostilidad sobrecontrolada, esto es: o son personas crónicamente agresivas o son individuos que expresan de manera bastante apropiada sus sentimientos de agresión."; break; case $score > 64: $text = "Los individuos que obtienen puntuaciones altas en la escala tienden a evitar la expresión abierta de la agresión sin embargo a menudo en momentos de extrema provocación, actúan de una manera muy violenta y pueden reaccionar con conductas acting out. Las personas con puntuaciones elevadas en HR, tienden a no expresar sentimientos de cólera, ni siquiera de manera verbal; son sociables y responsables y tienen una fuerte necesidad de sobresalir ante los demás; no obstante, son dependientes y confiados. Suelen describir a sus familias de origen como cálidas y fuentes de apoyo."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_Is1 = function($score){ switch($score){ case $score < 41: $text = "La escala es bipolar significa que las puntuaciones bajas indican lo contrario a las puntajes altos."; break; case $score > 64: $text = "Son tímidos en las situaciones interpersonales, muestran incomodidad al estar rodeados de otros y son reacios para iniciar relaciones. No se consideran a sí mismos como sociables. Las personas pueden mostrase tímidas con los demás, apenarse fácilmente, molestas en situaciones sociales e incomodas en situaciones nuevas."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_Is2 = function($score){ switch($score){ case $score < 41: $text = "La escala es bipolar significa que las puntuaciones bajas indican lo contrario a las puntajes altos."; break; case $score > 64: $text = "Tienden a evitar estar en grupo, son poco amigables, se aíslan socialmente y evitan participar con los demás. Quizá les disguste las fiestas y los bailes. Esta escala indica baja autoestima y poca confianza autocrítica, cuestionamiento del juicio propio y sentimientos de incapacidad para determinar el propio destino."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_Is3 = function($score){ switch($score){ case $score < 41: $text = "Puede ser una persona emotiva, desinhibida verbal, entusiasta, atrevida y alegre. También puede ser una persona generosa, impulsiva, agresiva, sarcástica, informal y autoindulgente, puede ser astuta, perspicaz, lista, sutil, engañosa y mentirosa. Además son extrovertidas, emotivas, espontáneas y su estilo de vida es dominante en sus relaciones interpersonales. Aparecen como enérgicas, expresivas informales. La interpretación de las puntuaciones bajas es indicativa de un individuo que es sociable, abierto, parlanchín, arriesgado, atrevido, vigoroso. Además es mandón, le gusta discutir, es egoísta, autoindulgente, perspicaz, precavido."; break; case $score < 64: $text = "Parece carecer de insight, es sobrecontrolador e inhibido socialmente, también se percibe a sí mismos y son percibidos por los demás como convencionales y reservados en el sentido emocional, amables y poco espontáneos. Tiende a evitar los conflictos en vez de tratarlos directamente debido a que suele ser sumiso y cauteloso. Otros lo ven como demasiado conservador en su conducta y acciones. Además se caracteriza por mostrar su pensamiento claro, ser lento en sus acciones y muy meticuloso. La interpretación de puntuaciones elevadas de la escala de represión es indicativa de un individuo formal, de ideas claras, cuidadoso."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_R = function($score){ switch($score){ case $score < 41: $text = "La escala es bipolar significa que las puntuaciones bajas indican lo contrario a los puntajes altos."; break; case $score > 64: $text = "Tienden a evitar estar en grupo, son poco amigables, se aíslan socialmente y evitan participar con los demás. Quizá les disguste las fiestas y los bailes. Indica disgusto y repudio a las actividades en grupo y al estar en multitudes, por lo que estos sujetos evitan el contacto con otras personas."; break; default: $text = "Puntuación normal"; break; } return $text; };

$sug_Rs = function($score){ switch($score){ case $score < 41: $text = "Quienes obtienen puntuaciones bajas en Rs, debajo de 40, se caracterizan por no estar dispuestas a asumir responsabilidades y tal vez no hayan aceptado valores o normas sociales; por otra parte no pueden ser vistos a sí mismos como poco dignos de confianza, faltos de integridad y con pobre sentido de responsabilidad para con el grupo."; break; case $score > 64: $text = "Las personas que tienen más de 25 años con puntuaciones altas tienden a aceptar su sistema de valores actual e intentan continuar utilizándolo, y quienes obtienen puntuaciones bajas pueden cuestionar su sistema de valores presente o rechazar los recién adquiridos. Para las personas más jóvenes, las puntuaciones RS altas indican que aceptan el sistema de valores de los padres, mientras que las puntuaciones bajas indican el cuestionamiento o rechazo del sistema de valores de los padres. Puntuaciones altas en RS sugieren que un individuo tiende a verse a sí mismo y ser visto por otras personas como dispuesto a aceptar las consecuencias de su propia conducta y como responsable, así mismo se le considera digno de confianza y persona íntegra, con sentido de responsabilidad para el grupo; además, es probable que se encuentre en situaciones de liderazgo y toma de decisiones. Puntuaciones altas arriba de 60, indican un fuerte sentido de justicia y un alto sentido a las normas, indican también que la persona tiene confianza en sí misma, es digna de confianza y responsable, y que posee, además, un sentido de compromiso social. Así mismo, están profundamente interesados en problemas éticos y morales: rechazan los privilegios y favores, y dan un énfasis excesivo al cumplimiento de su parte correspondiente de cargas y deberes."; break; default: $text = "Puntuación normal"; break; } return $text; };

if($_SESSION['genre'] == 'male'){
    $scoreB = $scoremB;
    $scoreC = $scoremC;
    $scoreS = $scoremS;
    $mf = $sug_Mfm($scoreB[7]);
}else{
    $scoreB = $scorefB;
    $scoreC = $scorefC;
    $scoreS = $scorefS;
    $mf = $sug_Mff($scoreB[7]);
}

$sugB = [
    $sug_L($scoreB[0]),
    $sug_F($scoreB[1]),
    $sug_K($scoreB[2]),
    $sug_Hs($scoreB[3]),
    $sug_D($scoreB[4]),
    $sug_Hi($scoreB[5]),
    $sug_Dp($scoreB[6]),
    $mf,
    $sug_Pa($scoreB[8]),
    $sug_Pt($scoreB[9]),
    $sug_Es($scoreB[10]),
    $sug_Ma($scoreB[11]),
    $sug_Is($scoreB[12])
];

$sugC = [
    $sug_ANS($scoreC[0]),
    $sug_MIE($scoreC[1]),
    $sug_OBS($scoreC[2]),
    $sug_DEP($scoreC[3]),
    $sug_SAU($scoreC[4]),
    $sug_DEL($scoreC[5]),
    $sug_ENJ($scoreC[6]),
    $sug_CIN($scoreC[7]),
    $sug_PAS($scoreC[8]),
    $sug_PTA($scoreC[9]),
    $sug_BAE($scoreC[10]),
    $sug_ISO($scoreC[11]),
    $sug_FAM($scoreC[12]),
    $sug_DTR($scoreC[13]),
    $sug_RTR($scoreC[14])
];

$sugS = [
    $sug_A($scoreS[0]),
    $sug_R($scoreS[1]),
    $sug_Fyo($scoreS[2]),
    $sug_AMAC($scoreS[3]),
    $sug_HR($scoreS[4]),
    $sug_Do($scoreS[5]),
    $sug_Rs($scoreS[6]),
    $sug_Dpr($scoreS[7]),
    $sug_GM($scoreS[8]),
    $sug_GF($scoreS[9]),
    $sug_EPK($scoreS[10]),
    $sug_EPS($scoreS[11]),
    $sug_Is1($scoreS[12]),
    $sug_Is2($scoreS[13]),
    $sug_Is3($scoreS[14]),
    $sug_Fp($scoreS[15])
];